#
#Filename:
#       remove_fold_diff.py
#
#Author:
#       Ian Goetting 
#
#Description:
#       This program will eliminate, from a genes training file, any genes that have a fold difference less than 2.
#       The output file generated by this program will only contain genes that have a fold difference greater than or equal to 2.
#Input:
#       This program takes command line arguments. 
#       The first argument is the input filename, the second argument is the output filename.
#       An example command to run this program would be: python normalize.py input.txt output.txt
#       Precondition: It is assumed that the input file already exists, otherwise an error will be generated.
#       The intended input file for this program is the pp5i_train.gr.csv that resulted from running run.sh from step 1.
#

import sys;
import string;

#Function that will remove genes from the training file that have a fold difference < 2
def normalize(input_filename, output_filename):
    input_file = open(input_filename, "r");
    output_file = open(output_filename, "w");
    #Skip the SNO line.
    SNO_line = input_file.readline();
    output_file.write(SNO_line);
    #Get the first actual line
    line = input_file.readline();
    #Remove genes where the fold difference is < 2
    while line:
        line_elements = string.split(line,',');
        skip_attribute_name = 1;
        first_element = 1;
        for element in line_elements:
            #Skip the first line in the file since it only contains IDs.
            if skip_attribute_name:
                skip_attribute_name = 0;
            else:
                new_element = float(element);
                #Set max and min values to new_element if its the first element we've seen
                if first_element:
                    max_value = new_element;
                    min_value = new_element;
                    first_element = 0;
                #Adjust max or min depending on the new_element's value
                if new_element < min_value:
                    min_value = new_element
                if new_element > max_value:
                    max_value = new_element;
        #If fold diff >= 2, write the line to the output file
        if (max_value/min_value) >= 2:
            output_file.write(line);
        line = input_file.readline();
    input_file.close();
    output_file.close();


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print "ERROR: An input filename and output filename must be given. e.g. python remove_fold_diff.py input.txt output.txt";
        sys.exit(0);
    elif sys.argv[1] == sys.argv[2]:
        print "ERROR: The input filename cannot be the same as the output filename!";
        sys.exit(0);
    normalize(sys.argv[1],sys.argv[2]);
